### ISSUE TITLE
bgm和b站无法使用

### ISSUE THREAD

**Issue by bosconb** [AkikoZ/alfred-web-search-suggest#13]
环境：macOS 10.14.3，alfred 4.01b1078

![image](https://user-images.githubusercontent.com/47100031/58763078-38b65d00-8589-11e9-936b-b0f62d42bbca.png)

![image](https://user-images.githubusercontent.com/47100031/58763081-4370f200-8589-11e9-907f-3a05125395bf.png)

**Comment by AkikoZ** [comment]
我这里正常。请检查是否使用了最新（目前为 v1.11）版本的 workflow。bgm请求相对较慢，稍等片刻就会显示出结果。
