### ISSUE TITLE
Shadowsocks设置socks代理模式无效

### ISSUE THREAD

**Issue by stevechoris** [AkikoZ/alfred-web-search-suggest#4]
我的Shadowsocks的1086端口是socks代理，1087端口是http代理。设置1086端口时无法使用google suggest，设置1087的时候可以。而且当设置1087的时候，proxy_type不管为CURLPROXY_HTTP还是CURLPROXY_SOCKS5都是有效的。
另外，如果直接修改request.ph，添加下面两行代码，设置1086端口的socks代理是有效的。
![image](https://user-images.githubusercontent.com/3997663/35084379-a1c92ac6-fc5e-11e7-9cff-d4b425320731.png)

**Comment by AkikoZ** [comment]
感谢反馈。已查明原因是 Alfred 在传 environment variables 的时候统一把参数转成了字符串，而 PROXYTYPE 实际是一个整形常量，导致该环境变量无效。因为我一直用的 HTTP 代理所以没注意到这个问题... 下一个版本会通过修改传入环境变量的格式加以修复。
