### ISSUE TITLE
建议增加默认的搜索词

### ISSUE THREAD

**Issue by stevechoris** [AkikoZ/alfred-web-search-suggest#5]
另外提一个小建议，就是使用suggest的时候有时候没有合适的suggest结果或者就是想搜输入的词，这时候就比较苦恼。建议可以在所有suggest中把默认的词始终放在第一位。

**Comment by AkikoZ** [comment]
哦这个的话，[这里](https://github.com/AkikoZ/alfred-web-search-suggest#direct-search)提供了一个解决方案，可以以相同的关键字把相应网站加到 Alfred 本身的 Web Search 里面，个人觉得这样更灵活些。

**Comment by stevechoris** [comment]
这个知道的，但是我一般会直接通过快捷键调用web-search-suggest，因此集成到一起会更方便。

**Comment by AkikoZ** [comment]
我这边还有一个考虑是搜索建议的回显会有一个网络请求的延时，因此如果想跳过建议直接搜索的话其实还是现在的方法快些。毕竟调用搜索的关键字都很简短，应该不会造成太大的不便。
