### ISSUE TITLE
shadowsocks下google还是不行

### ISSUE THREAD

**Issue by wjx0912** [AkikoZ/alfred-web-search-suggest#6]
chrome和safari都可以访问google，但是alfred gg还是不行(百度正常)，可以协助测试 qq:80101277
谢谢

**Comment by wjx0912** [comment]
我的 shadowsocks 可以免费给您用，希望帮忙解决下

**Comment by AkikoZ** [comment]
请务必参照[这里](https://github.com/AkikoZ/alfred-web-search-suggest#proxy-setting)的说明对 Alfred Workflow 的环境变量（下图红圈处的按钮）进行正确的配置。
例：如果你使用的客户端是 [ShadowsocksX-NG](https://github.com/shadowsocks/ShadowsocksX-NG) 且没有修改过其高级配置，那么在 `proxy` 变量右边的 Value 一栏填入 `http://127.0.0.1:1087` 即可。
<img width="842" alt="2018-02-06 11 06 17" src="https://user-images.githubusercontent.com/22231232/35839926-0c3f7bb6-0b2e-11e8-89a8-5e490ea1e1ec.png">

**Comment by wjx0912** [comment]
感谢作者。正常工作了，需要ss可用联系我~~
