### ISSUE TITLE
请问一下 如何搜索amazon呢？ 

### ISSUE THREAD

**Issue by zhiyicai** [AkikoZ/alfred-web-search-suggest#7]
请问一下 如何搜索amazon呢？ 
找到了 amazon url 但是不知道如何设置.
http://completion.amazon.com/search/complete?search-alias=aps&client=amazon-search-ui&mkt=1&q=canon

**Comment by AkikoZ** [comment]
不好意思，当前版本尚没有 Amazon 的搜索建议功能，我会考虑在下个版本加入的。

**Comment by AkikoZ** [comment]
v1.9 已加入 Amazon 搜索建议。
